<form id="user_form" action="user/update" method="post" autocomplete="off" class="form-horizontal" role="form">
    <div class="form-group">
        <label for="login_name" class="col-xs-2 control-label">Username</label>
        <div class="col-xs-2">
            <input name="username" type="text" maxlength="15" class="form-control" placeholder="Username" required autofocus>
        </div>
    </div>
    <div class="form-group">
        <label for="person_name" class="col-xs-2 control-label">Nama</label>
        <div class="col-xs-2">
            <input name="first_name" type="text" maxlength="15" class="form-control" placeholder="Nama Depan" required>
        </div>
        <div class="col-xs-2">
            <input name="last_name" type="text" maxlength="15" class="form-control" placeholder="Nama Belakang">
        </div>
    </div>
    <div class="form-group">
        <label for="company_name" class="col-xs-2 control-label">Nama Perusahaan</label>
        <div class="col-xs-4">
            <input name="company_name" type="text" maxlength="35" class="form-control" placeholder="Nama Perusahaan" required>
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-xs-2 control-label">Email</label>
        <div class="col-xs-4">
            <input name="email" type="email" maxlength="25" class="form-control" placeholder="Email">
        </div>
    </div>
</form>