<div class="row">
    <div class="col-xs-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Tabel Responden</h3>
                <div class="box-tools pull-right">
                    <button id="btn-add-kriteria" type="button" class="btn btn-info" title="Tambah Responden Baru">
                        <i class="fa fa-user-plus"></i> Tambah Baru
                    </button>
                </div>
            </div><!-- /.box-header -->

            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th style="width: 40px">#</th>
                            <th style="width: 150px">Username</th>
                            <th style="width: 300px">Nama</th>
                            <th style="width: 300px">Email</th>
                            <th>Keterangan</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="success">
                            <td>1</td>
                            <td>Ulala</td>
                            <td>Eulala Lala Ulala</td>
                            <td>laulala@ul.com</td>
                            <td>Active</td>
                            <td>
                                <div class="actions-btn transparent-btn">
                                    <button style="color: #f0ad4e">
                                        <i class="ion ion-pause" title="Suspend"></i>
                                    </button>
                                    <button style="color: #d43f3a">
                                        <i class="fa fa-ban" title="Ban"></i>
                                    </button>
                                    <button style="color: #d43f3a">
                                        <i class="fa fa-user-times" title="Delete"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div><!-- /.box-body -->

        </div>
    </div>
</div>