<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <title>Seleksi Supplier | Log In</title>
        <link rel="stylesheet" href="css/calm-breeze-login-style.css">
    </head>

    <body>
        <div class="wrapper">
            <div class="container">
                <h1>Welcome</h1>
                <form class="form">
                    <div>
                        <input name="uname" type="text" placeholder="Username">
                    </div>
                    <div>
                        <input name="password" type="password" placeholder="Password">
                    </div>
                    <button type="submit" id="login-button">Login</button>
                </form>
                <div class="preloader-img"></div>
            </div>

            <ul class="bg-bubbles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div><!-- /.wrapper -->
        
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/calm-breeze-login.js"></script>
    </body>
</html>
