<li>
    <a href="/">
        <i class="fa fa-home fa-fw"></i>
        <span>Home</span>
    </a>
</li>
<?php if ($responden) { ?>
<li>
    <a href="kuesioner">
        <i class="fa fa-file-text-o fa-fw"></i>
        <span>Kuesioner</span>
    </a>
</li>
<?php } else { ?>
<li class="treeview">
    <a href="#">
        <i class="fa fa-wrench fa-fw"></i>
        <span>AdministrationTools</span>
        <i class="fa fa-plus-square-o fa-fw pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="kriteria"><i class="fa fa-chevron-right"></i> Kriteria</a></li>
        <li><a href="kuesioner"><i class="fa fa-chevron-right"></i> Kuesioner</a></li>
        <li><a href="responden"><i class="fa fa-chevron-right"></i> Responden</a></li>
    </ul>
</li>
<?php } ?>