<!DOCTYPE html>
<html>
    <head>
        <title>Seleksi Supplier | <?php echo $data["menu"];?></title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
        <!-- inferno style -->
        <link rel="stylesheet" type="text/css" href="css/this-style.css">
        <!-- AdminLTE Theme style -->
        <link rel="stylesheet" type="text/css" href="css/AdminLTE.css">
        <!-- ionicons style -->
        <link rel="stylesheet" type="text/css" href="css/ionicons.min.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="skin-blue">
        <header class="header">
            <?php $this->partial("_top_navbar"); ?>
        </header>
        <!--  -->
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="img/avatar3.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Hello, <?php echo explode(" ", $this->session->get("auth")["user"]->getName())[0]; ?></p>
    
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- sidebar menu: -->
                    <ul class="sidebar-menu">
                        <?php $this->partial("_menu"); ?>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>
    
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <i class="<?php echo $data["menu_icon_class"];?>"></i>
                        <?php
                            echo $data ["menu"];
                            if (isset ( $data ["menu_desc"] ))
                                echo "<small>".$data["menu_desc"]."</small>";
                        ?>
                    </h1><?php if ($data["menu"] != "Home") {?>
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active"><?php echo $data["menu"];?></li>
                    </ol><?php }?>
                </section>
    
                <!-- Main content -->
                <section class="content">
                    <?php echo $this->flashSession->output(); ?>
                    <?php echo $this->getContent(); ?>
                </section>
            </aside>
        </div>
        <!-- scripts include section -->
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="js/AdminLTE/app.js"></script>
        <script type="text/javascript" src="js/AdminLTE/dashboard.js"></script>
        <!-- my javascripts file -->
        <script type="text/javascript" src="js/my-jscript.js"></script>
    </body>
</html>